title: Western Water Datahub EDR Guide
description: Documentation for using the Western Water Datahub EDR API.
url: "https://ksonda.github.io"
baseurl: "/wwdh-edr-docs"
repository: "ksonda/wwdh-edr-docs"

theme: null
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .bundle
  - .github
  - node_modules
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
